config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :cities
    resources :themes
    resources :events
    resources :filters

    root to: 'events#index'
  end

  root to: 'events#show'

  resource :events, only: [:show] do
    get 'filter', to: 'events#filter'
    post 'filter/save', to: 'events#save_filter', as: :save_filter
  end

  get 'filter/delete/:id', to: 'filter#delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :events
  has_many :filters
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :city
  has_and_belongs_to_many :themes

  paginates_per 10

  scope :with_relations, -> { includes(:city, :themes) }
  scope :by_city, ->(city_id) { where(city_id: city_id) }
  scope :by_themes, ->(theme_ids) { joins(:themes).merge(Theme.where(id: theme_ids)) }

  scope :get_from_date, ->(from) { where("`from` >= :date", date: from.to_date) }
  scope :get_to_date,   ->(to)   { where("`to` <= :date",   date: to.to_date  ) }
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :city, optional: true
  has_and_belongs_to_many :themes
end

app/models/theme.rb
class Theme < ApplicationRecord

  has_and_belongs_to_many :events
  has_and_belongs_to_many :themes

end

app/models/user.rb
class User < ApplicationRecord

  self.abstract_class = true

  def self.current
    'user'
  end

  def self.queue_name
    "#{current}_list"
  end

  def self.online?
    Rails.cache.redis.get(current)
  end

  def self.set_online
    Rails.cache.redis.set(current, true)
  end

  def self.set_offline
    Rails.cache.redis.del(current)
  end

  def self.add_to_queue(value)
    Rails.cache.redis.rpush(queue_name, value)
  end

  def self.broadcast(data)
    EventChannel.broadcast_to User.current, event: data
  end

  def self.notify_from_offline
    count = Rails.cache.redis.llen(queue_name)

    (1..count).each do
      data = Rails.cache.redis.lpop(queue_name)
      broadcast data
    end
  end

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/cities_controller.rb
module Admin
  class CitiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = City.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   City.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Event.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Event.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
    #

    def create
      super

      event = Event.last

      User.online? ? User.broadcast(event.to_json) : User.add_to_queue(event.to_json)
    end

  end
end

app/controllers/admin/filters_controller.rb
module Admin
  class FiltersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Filter.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Filter.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/themes_controller.rb
module Admin
  class ThemesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Theme.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Theme.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def json_error
    render json: { success: false }
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def list
    @city_list = City.all
  end

  def check
    if params[:city_id].to_i.zero?
      cookies.delete :city_id
    else
      cookies[:city_id] = { value: params[:city_id], expires: Time.now + 1.year }
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  helper FilterHelper

  def show
    @events = Event.all.page(params[:page])
    create_filter
    filter_events
  end

  def save_filter
    create_filter

    begin
      @filter.save!
    rescue
      return render json: { success: false }
    end

    render json: { success: true }
  end


  private

  def filter_params
    params.permit(filter: [:title, :city_id, :from, :to,])[:filter]
  end

  def theme_ids_params
    params.permit(themes: [ids: []]).fetch(:themes, {}).fetch(:ids, [])
  end

  def create_filter
    @filter = Filter.new(filter_params)
    @filter.themes << Theme.find(theme_ids_params)
  end

  def filter_events
    filter_by_city
    filter_by_theme
    filter_by_range
  end

  def filter_by_city
    @events = @events.by_city(@filter.city_id) if @filter.city_id&.positive?
  end

  def filter_by_theme
    if @filter.themes && !@filter.themes.empty?
      @events = @events.by_themes(@filter.themes.map(&:id))
    end
  end

  def filter_by_range
    @events = @events.get_from_date(@filter.from) if @filter.from
    @events = @events.get_to_date(@filter.to)     if @filter.to
  end

end

app/controllers/filter_controller.rb
class FilterController < ApplicationController

  rescue_from Exception, with: :json_error

  def delete
    Filter.delete(params[:id])
    render json: { success: true }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filter_helper.rb
module FilterHelper

  def filter_url(filter)
    @filter = filter
    link_to filter.title.to_s, events_path(params: filter_params)
  end

  def filter_params
    {
      themes: {
        ids: @filter.themes.map(&:id),
      },
      filter: {
        city_id: @filter.city_id,
        from: @filter.from,
        to: @filter.to,
      }.delete_if { |k, _| k.nil? }
    }
  end

end

app/views/events/_custom_fields_list.html.erb
<div>
    <label>Saved filters list</label>
    <ul>
        <% Filter.all.each do |filter| %>
            <li>
                <%= filter_url(filter) %>
                <button class="btn btn-xs delete-filter-button" data-id="<%= filter.id %>">Delete</button>
            </li>
        <% end %>
    </ul>
</div>

<script>
    $('.delete-filter-button').click(function () {
        let $el = $(this)

        $.ajax({
            url: '/filter/delete/' +  $(this).data('id')
        })
        .done(function (answer) {
            if ( answer.success ) {
                $el.parent().remove()
            }
            else {
                alert(answer.message)
            }
        })
        .fail(function () {
            alert('Fail')
        })
    })
</script>

app/views/events/_event_list.html.erb
<div>
    <% @events.each do |event| %>
        <h2><%= event.title %> <span><%= event.city.title %></span></h2>
        <p><%= event.from %> - <%= event.to %></p>
        <%= event.themes.map(&:title).join(', ') %>
    <% end %>
    <%= paginate @events %>
</div>

app/views/events/_filters.html.erb
<div>
    <h5>Filters</h5>

    <form id="filters">
        <div class="form-group">
            <label for="city">Select themes</label>
            <%= select :filter, :city_id, options_from_collection_for_select(City.all, "id", "title", @filter.city_id), {include_blank: "All cities"}, {id: "city"} %>
        </div>

        <div class="form-group">
            <label for="theme">Select themes</label>
            <%= select :themes, :ids, options_from_collection_for_select(Theme.all, "id", "title", @filter.themes.map(&:id)), {include_hidden: false}, {id: "theme", class: "form-control", multiple: true}  %>
        </div>

        <div class="form-group">
            <label>Select date range</label>
            <%= text_field :filter, :from, class: "form-control datefield", id: "date-from-field", placeholder: "Select from..." %>
            <%= text_field :filter, :to, class: "form-control datefield", id: "date-to-field", placeholder: "Select to..." %>
        </div>

        <button type="submit">Filter</button>
        <a href="<%= root_path() %>">Clear filter</a>
    </form>

    <form id="save-filter-form">
        <%= token_tag %>
        <input name="filter[title]" placeholder="Filter title"/>
        <button type="submit">Save filter</button>
    </form>

    <%= render "custom_fields_list" %>
</div>

<script>
    $("#save-filter-form").submit(function (e) {
        e.preventDefault();
        $.ajax({
            url: '<%= save_filter_events_path %>',
            method: 'POST',
            data: $('#save-filter-form').serializeArray().concat($('#filters').serializeArray())
        })
    })
</script>

app/views/events/show.html.erb
<%= render "filters" %>

<%= render "event_list" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeyvnTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            flatpickr('#date-from-field');
            flatpickr('#date-to-field')
        })
    </script>
  </body>
</html>